name: docgen

defaults:
  run:
    shell: pwsh

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download PowerShell packages to test against
      run: .\downloadPwshPackages.ps1

    - name: Run tests
      run: |
        Install-Module -Name Pester -Force
        .\runTests.ps1

    - name: Generate the doc HTML file
      run: .\generateHtml.ps1 > .\index.html

    - name: Upload the HTML file as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: .\index.html

    - name: Upload the CSS file as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: .\style.css

  deploy:
    runs-on: windows-latest
    needs: build
    if: ${{ github.event_name == 'push' }}
    steps:
    - uses: actions/checkout@v2

    - name: Download the site to the webroot
      uses: actions/download-artifact@v2
      with:
        name: site
        path: .\webroot\

    - name: Deploy the docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .\webroot\
