name: docgen

defaults:
  run:
    shell: pwsh

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: |
        Install-Module -Name Pester -Force
        .\runTests.ps1

    - name: Generate the doc HTML file
      run: .\generateHtml.ps1 > .\pwsh-live-doc.html

    - name: Upload the HTML file as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: pwsh-live-doc
        path: .\pwsh-live-doc.html

  deploy:
    runs-on: windows-latest
    needs: build
    if: ${{ github.event_name == 'push' }}
    steps:
    - uses: actions/checkout@v2

    - name: Download the HTML file
      uses: actions/download-artifact@v2
      with:
        name: pwsh-live-doc

    - name: Create a webroot directory and put the HTML file in it
      run: |
        mkdir .\webroot
        mv .\pwsh-live-doc.html .\webroot\index.html

    - name: Deploy the docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .\webroot
